name: jobs & steps

on: workflow_dispatch

env:
  GREETINGS: "welcome to github actions"

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: calling variable
        run: echo "$GREETINGS"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build started
        run: echo "build started"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: build status
        run: echo "$GREETINGS, build completed"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: testing the artifacts
        run: echo "testing is completed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "deployment completed"
