name: Jobs & Steps

on: workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build started
        run: echo "build started"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: check the code 
        run: ls -a
