name: secrets and variables

on: workflow_dispatch

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: calling secrets
        run: echo "my db password is ${{ secrets.DB_PASSWORD }} and port is ${{ secrets.DB_PORT }}"

  variables:
    runs-on: ubuntu-latest
    steps:
      - name: calling github variable
        run: echo "my database name is ${{ vars.DBNAME }} and the username is ${{ vars.DB_USER }}"
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          # Username used to log against the Docker registry
          username: ${{ vars.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

  docker-signin:
    runs-on: ubuntu-latest
    steps:
      - name: docker manual login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin      
