name: secrets and variables

on: workflow_dispatch

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: calling secrets
        run: echo "my db password is ${{ secrets.DB_PASSWORD }} and port is ${{ secrets.DB_PORT }}"

  variables:
    runs-on: ubuntu-latest
    steps:
      - name: calling github variable
        run: echo "my database name is ${{ vars.DBNAME }} and the username is ${{ vars.DB_USER }}"
